---
# tasks file for nginx
- name: Install nginx
  apt: name=nginx state=latest

- name: Start and Enable
  service: name=nginx state=started enabled=yes
  ignore_errors: true

- name: Open ports
  ufw:
    rule: allow
    port: 80
    proto: tcp


- name: Change hello page 1
  template:
    src: index1.html
    dest: /var/www/html/index.html
  when: "'web1' in inventory_hostname"

- name: Change hello page 2
  template:
    src: index2.html
    dest: /var/www/html/index.html
  when: "'web2' in inventory_hostname"

