---
# tasks file for dnsmasq
- name: Install dnsmasq package
  ansible.builtin.apt:
    name: "dnsmasq"
    state: present
  
- name: Stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped

- name: "Copy dnsmasq.conf"
  copy:
    src: dnsmasq.conf
    dest: "/etc/dnsmasq.d/dnsmasq.conf"
  notify: "setup dnsmasq"