---
# tasks file for keepalived
- name: Install keepalived
  apt: name=keepalived state=latest

- name: Copy master configs
  copy:
    src: keepalivedMASTER.conf
    dest: /etc/keepalived/keepalived.conf
  when: "'ha1' in inventory_hostname"

- name: Copy slave configs
  copy:
    src: keepalivedSLAVE.conf
    dest: /etc/keepalived/keepalived.conf
  when: "'ha2' in inventory_hostname"

- name: Copy script
  copy:
    src: check_nginx.sh
    dest: /bin/check_nginx.sh
    mode: 0755

- name: Start and Enable
  service: name=keepalived state=started enabled=yes
  ignore_errors: true