version: '3'

services:
  app:
    build: 
      context: ./django-docker
      dockerfile: Dockerfile.prod
    command: gunicorn djangodocker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres:
  static: