version: '3'

services:
  app:
    build: 
      context: ./django-docker
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-docker/:/opt/django/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=QWEASDZXC
      - POSTGRES_PASSWORD=QWEASDZXC
      - POSTGRES_DB=QWEQWEQWE

volumes:
  postgres_data:
